// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/tonitomc/healthcare-crm-api/internal/domain/medicalrecord/models"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(patientID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", patientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(patientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), patientID)
}

// GetByPatientID mocks base method.
func (m *MockRepository) GetByPatientID(patientID int) (*models.MedicalRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPatientID", patientID)
	ret0, _ := ret[0].(*models.MedicalRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPatientID indicates an expected call of GetByPatientID.
func (mr *MockRepositoryMockRecorder) GetByPatientID(patientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPatientID", reflect.TypeOf((*MockRepository)(nil).GetByPatientID), patientID)
}

// Update mocks base method.
func (m *MockRepository) Update(patientID int, record *models.MedicalRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", patientID, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(patientID, record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), patientID, record)
}
