// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/tonitomc/healthcare-crm-api/internal/domain/reminder/models"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(userID int, desc string, global bool) (*models.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userID, desc, global)
	ret0, _ := ret[0].(*models.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(userID, desc, global interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), userID, desc, global)
}

// Delete mocks base method.
func (m *MockService) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), id)
}

// GetForUser mocks base method.
func (m *MockService) GetForUser(userID int) ([]models.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUser", userID)
	ret0, _ := ret[0].([]models.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUser indicates an expected call of GetForUser.
func (mr *MockServiceMockRecorder) GetForUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUser", reflect.TypeOf((*MockService)(nil).GetForUser), userID)
}

// SetDone mocks base method.
func (m *MockService) SetDone(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDone", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDone indicates an expected call of SetDone.
func (mr *MockServiceMockRecorder) SetDone(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDone", reflect.TypeOf((*MockService)(nil).SetDone), id)
}

// SetUndone mocks base method.
func (m *MockService) SetUndone(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUndone", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUndone indicates an expected call of SetUndone.
func (mr *MockServiceMockRecorder) SetUndone(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUndone", reflect.TypeOf((*MockService)(nil).SetUndone), id)
}
