// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/tonitomc/healthcare-crm-api/internal/domain/consultation/models"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddAnswers mocks base method.
func (m *MockRepository) AddAnswers(a *models.Answers) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAnswers", a)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAnswers indicates an expected call of AddAnswers.
func (mr *MockRepositoryMockRecorder) AddAnswers(a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAnswers", reflect.TypeOf((*MockRepository)(nil).AddAnswers), a)
}

// Create mocks base method.
func (m *MockRepository) Create(consultation *models.Consultation) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", consultation)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(consultation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), consultation)
}

// CreateDiagnostic mocks base method.
func (m *MockRepository) CreateDiagnostic(d *models.Diagnostic) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiagnostic", d)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiagnostic indicates an expected call of CreateDiagnostic.
func (mr *MockRepositoryMockRecorder) CreateDiagnostic(d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiagnostic", reflect.TypeOf((*MockRepository)(nil).CreateDiagnostic), d)
}

// CreateTreatment mocks base method.
func (m *MockRepository) CreateTreatment(t *models.Treatment) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTreatment", t)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTreatment indicates an expected call of CreateTreatment.
func (mr *MockRepositoryMockRecorder) CreateTreatment(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTreatment", reflect.TypeOf((*MockRepository)(nil).CreateTreatment), t)
}

// Delete mocks base method.
func (m *MockRepository) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), id)
}

// DeleteAnswers mocks base method.
func (m *MockRepository) DeleteAnswers(consultationID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnswers", consultationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnswers indicates an expected call of DeleteAnswers.
func (mr *MockRepositoryMockRecorder) DeleteAnswers(consultationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnswers", reflect.TypeOf((*MockRepository)(nil).DeleteAnswers), consultationID)
}

// DeleteDiagnostic mocks base method.
func (m *MockRepository) DeleteDiagnostic(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiagnostic", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiagnostic indicates an expected call of DeleteDiagnostic.
func (mr *MockRepositoryMockRecorder) DeleteDiagnostic(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiagnostic", reflect.TypeOf((*MockRepository)(nil).DeleteDiagnostic), id)
}

// DeleteTreatment mocks base method.
func (m *MockRepository) DeleteTreatment(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTreatment", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTreatment indicates an expected call of DeleteTreatment.
func (mr *MockRepositoryMockRecorder) DeleteTreatment(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTreatment", reflect.TypeOf((*MockRepository)(nil).DeleteTreatment), id)
}

// GetAll mocks base method.
func (m *MockRepository) GetAll() ([]models.Consultation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Consultation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepository)(nil).GetAll))
}

// GetAnswersByConsultation mocks base method.
func (m *MockRepository) GetAnswersByConsultation(consultationID int) (*models.Answers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnswersByConsultation", consultationID)
	ret0, _ := ret[0].(*models.Answers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnswersByConsultation indicates an expected call of GetAnswersByConsultation.
func (mr *MockRepositoryMockRecorder) GetAnswersByConsultation(consultationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnswersByConsultation", reflect.TypeOf((*MockRepository)(nil).GetAnswersByConsultation), consultationID)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(id int) (*models.Consultation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Consultation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), id)
}

// GetByPatient mocks base method.
func (m *MockRepository) GetByPatient(patientID int) ([]models.Consultation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPatient", patientID)
	ret0, _ := ret[0].([]models.Consultation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPatient indicates an expected call of GetByPatient.
func (mr *MockRepositoryMockRecorder) GetByPatient(patientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPatient", reflect.TypeOf((*MockRepository)(nil).GetByPatient), patientID)
}

// GetDiagnosticByID mocks base method.
func (m *MockRepository) GetDiagnosticByID(id int) (*models.Diagnostic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiagnosticByID", id)
	ret0, _ := ret[0].(*models.Diagnostic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiagnosticByID indicates an expected call of GetDiagnosticByID.
func (mr *MockRepositoryMockRecorder) GetDiagnosticByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiagnosticByID", reflect.TypeOf((*MockRepository)(nil).GetDiagnosticByID), id)
}

// GetDiagnosticsByConsultation mocks base method.
func (m *MockRepository) GetDiagnosticsByConsultation(consultationID int) ([]models.Diagnostic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiagnosticsByConsultation", consultationID)
	ret0, _ := ret[0].([]models.Diagnostic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiagnosticsByConsultation indicates an expected call of GetDiagnosticsByConsultation.
func (mr *MockRepositoryMockRecorder) GetDiagnosticsByConsultation(consultationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiagnosticsByConsultation", reflect.TypeOf((*MockRepository)(nil).GetDiagnosticsByConsultation), consultationID)
}

// GetTreatmentByID mocks base method.
func (m *MockRepository) GetTreatmentByID(id int) (*models.Treatment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreatmentByID", id)
	ret0, _ := ret[0].(*models.Treatment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreatmentByID indicates an expected call of GetTreatmentByID.
func (mr *MockRepositoryMockRecorder) GetTreatmentByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreatmentByID", reflect.TypeOf((*MockRepository)(nil).GetTreatmentByID), id)
}

// GetTreatmentsByDiagnostic mocks base method.
func (m *MockRepository) GetTreatmentsByDiagnostic(diagnosticID int) ([]models.Treatment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreatmentsByDiagnostic", diagnosticID)
	ret0, _ := ret[0].([]models.Treatment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreatmentsByDiagnostic indicates an expected call of GetTreatmentsByDiagnostic.
func (mr *MockRepositoryMockRecorder) GetTreatmentsByDiagnostic(diagnosticID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreatmentsByDiagnostic", reflect.TypeOf((*MockRepository)(nil).GetTreatmentsByDiagnostic), diagnosticID)
}

// Update mocks base method.
func (m *MockRepository) Update(consultation *models.Consultation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", consultation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(consultation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), consultation)
}

// UpdateAnswers mocks base method.
func (m *MockRepository) UpdateAnswers(a *models.Answers) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnswers", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnswers indicates an expected call of UpdateAnswers.
func (mr *MockRepositoryMockRecorder) UpdateAnswers(a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnswers", reflect.TypeOf((*MockRepository)(nil).UpdateAnswers), a)
}

// UpdateDiagnostic mocks base method.
func (m *MockRepository) UpdateDiagnostic(d *models.Diagnostic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiagnostic", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDiagnostic indicates an expected call of UpdateDiagnostic.
func (mr *MockRepositoryMockRecorder) UpdateDiagnostic(d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiagnostic", reflect.TypeOf((*MockRepository)(nil).UpdateDiagnostic), d)
}

// UpdateTreatment mocks base method.
func (m *MockRepository) UpdateTreatment(t *models.Treatment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTreatment", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTreatment indicates an expected call of UpdateTreatment.
func (mr *MockRepositoryMockRecorder) UpdateTreatment(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTreatment", reflect.TypeOf((*MockRepository)(nil).UpdateTreatment), t)
}
