// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	json "encoding/json"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/tonitomc/healthcare-crm-api/internal/domain/consultation/models"
)

// MockQuestionnaireValidator is a mock of QuestionnaireValidator interface.
type MockQuestionnaireValidator struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionnaireValidatorMockRecorder
}

// MockQuestionnaireValidatorMockRecorder is the mock recorder for MockQuestionnaireValidator.
type MockQuestionnaireValidatorMockRecorder struct {
	mock *MockQuestionnaireValidator
}

// NewMockQuestionnaireValidator creates a new mock instance.
func NewMockQuestionnaireValidator(ctrl *gomock.Controller) *MockQuestionnaireValidator {
	mock := &MockQuestionnaireValidator{ctrl: ctrl}
	mock.recorder = &MockQuestionnaireValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionnaireValidator) EXPECT() *MockQuestionnaireValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockQuestionnaireValidator) Validate(questionnaireID int, answers json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", questionnaireID, answers)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockQuestionnaireValidatorMockRecorder) Validate(questionnaireID, answers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockQuestionnaireValidator)(nil).Validate), questionnaireID, answers)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddAnswers mocks base method.
func (m *MockService) AddAnswers(consultaID int, dto *models.AnswersCreateDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAnswers", consultaID, dto)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAnswers indicates an expected call of AddAnswers.
func (mr *MockServiceMockRecorder) AddAnswers(consultaID, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAnswers", reflect.TypeOf((*MockService)(nil).AddAnswers), consultaID, dto)
}

// Create mocks base method.
func (m *MockService) Create(dto *models.ConsultationCreateDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", dto)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), dto)
}

// CreateDiagnostic mocks base method.
func (m *MockService) CreateDiagnostic(dto *models.DiagnosticCreateDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiagnostic", dto)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiagnostic indicates an expected call of CreateDiagnostic.
func (mr *MockServiceMockRecorder) CreateDiagnostic(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiagnostic", reflect.TypeOf((*MockService)(nil).CreateDiagnostic), dto)
}

// CreateTreatment mocks base method.
func (m *MockService) CreateTreatment(dto *models.TreatmentCreateDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTreatment", dto)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTreatment indicates an expected call of CreateTreatment.
func (mr *MockServiceMockRecorder) CreateTreatment(dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTreatment", reflect.TypeOf((*MockService)(nil).CreateTreatment), dto)
}

// Delete mocks base method.
func (m *MockService) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), id)
}

// DeleteAnswers mocks base method.
func (m *MockService) DeleteAnswers(consultaID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnswers", consultaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnswers indicates an expected call of DeleteAnswers.
func (mr *MockServiceMockRecorder) DeleteAnswers(consultaID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnswers", reflect.TypeOf((*MockService)(nil).DeleteAnswers), consultaID)
}

// DeleteDiagnostic mocks base method.
func (m *MockService) DeleteDiagnostic(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiagnostic", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiagnostic indicates an expected call of DeleteDiagnostic.
func (mr *MockServiceMockRecorder) DeleteDiagnostic(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiagnostic", reflect.TypeOf((*MockService)(nil).DeleteDiagnostic), id)
}

// DeleteTreatment mocks base method.
func (m *MockService) DeleteTreatment(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTreatment", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTreatment indicates an expected call of DeleteTreatment.
func (mr *MockServiceMockRecorder) DeleteTreatment(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTreatment", reflect.TypeOf((*MockService)(nil).DeleteTreatment), id)
}

// GetAll mocks base method.
func (m *MockService) GetAll() ([]models.Consultation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Consultation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll))
}

// GetAnswersByConsultation mocks base method.
func (m *MockService) GetAnswersByConsultation(consultationID int) (*models.Answers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnswersByConsultation", consultationID)
	ret0, _ := ret[0].(*models.Answers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnswersByConsultation indicates an expected call of GetAnswersByConsultation.
func (mr *MockServiceMockRecorder) GetAnswersByConsultation(consultationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnswersByConsultation", reflect.TypeOf((*MockService)(nil).GetAnswersByConsultation), consultationID)
}

// GetByID mocks base method.
func (m *MockService) GetByID(id int) (*models.Consultation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Consultation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), id)
}

// GetByPatient mocks base method.
func (m *MockService) GetByPatient(patientID int) ([]models.Consultation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPatient", patientID)
	ret0, _ := ret[0].([]models.Consultation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPatient indicates an expected call of GetByPatient.
func (mr *MockServiceMockRecorder) GetByPatient(patientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPatient", reflect.TypeOf((*MockService)(nil).GetByPatient), patientID)
}

// GetByPatientWithDetails mocks base method.
func (m *MockService) GetByPatientWithDetails(patientID int) ([]models.ConsultationWithDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPatientWithDetails", patientID)
	ret0, _ := ret[0].([]models.ConsultationWithDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPatientWithDetails indicates an expected call of GetByPatientWithDetails.
func (mr *MockServiceMockRecorder) GetByPatientWithDetails(patientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPatientWithDetails", reflect.TypeOf((*MockService)(nil).GetByPatientWithDetails), patientID)
}

// GetDiagnosticByID mocks base method.
func (m *MockService) GetDiagnosticByID(id int) (*models.Diagnostic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiagnosticByID", id)
	ret0, _ := ret[0].(*models.Diagnostic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiagnosticByID indicates an expected call of GetDiagnosticByID.
func (mr *MockServiceMockRecorder) GetDiagnosticByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiagnosticByID", reflect.TypeOf((*MockService)(nil).GetDiagnosticByID), id)
}

// GetDiagnosticsByConsultation mocks base method.
func (m *MockService) GetDiagnosticsByConsultation(consultationID int) ([]models.Diagnostic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiagnosticsByConsultation", consultationID)
	ret0, _ := ret[0].([]models.Diagnostic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiagnosticsByConsultation indicates an expected call of GetDiagnosticsByConsultation.
func (mr *MockServiceMockRecorder) GetDiagnosticsByConsultation(consultationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiagnosticsByConsultation", reflect.TypeOf((*MockService)(nil).GetDiagnosticsByConsultation), consultationID)
}

// GetTreatmentByID mocks base method.
func (m *MockService) GetTreatmentByID(id int) (*models.Treatment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreatmentByID", id)
	ret0, _ := ret[0].(*models.Treatment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreatmentByID indicates an expected call of GetTreatmentByID.
func (mr *MockServiceMockRecorder) GetTreatmentByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreatmentByID", reflect.TypeOf((*MockService)(nil).GetTreatmentByID), id)
}

// GetTreatmentsByDiagnostic mocks base method.
func (m *MockService) GetTreatmentsByDiagnostic(diagnosticID int) ([]models.Treatment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreatmentsByDiagnostic", diagnosticID)
	ret0, _ := ret[0].([]models.Treatment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreatmentsByDiagnostic indicates an expected call of GetTreatmentsByDiagnostic.
func (mr *MockServiceMockRecorder) GetTreatmentsByDiagnostic(diagnosticID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreatmentsByDiagnostic", reflect.TypeOf((*MockService)(nil).GetTreatmentsByDiagnostic), diagnosticID)
}

// MarkComplete mocks base method.
func (m *MockService) MarkComplete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkComplete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkComplete indicates an expected call of MarkComplete.
func (mr *MockServiceMockRecorder) MarkComplete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkComplete", reflect.TypeOf((*MockService)(nil).MarkComplete), id)
}

// MarkPending mocks base method.
func (m *MockService) MarkPending(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPending", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPending indicates an expected call of MarkPending.
func (mr *MockServiceMockRecorder) MarkPending(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPending", reflect.TypeOf((*MockService)(nil).MarkPending), id)
}

// Update mocks base method.
func (m *MockService) Update(id int, dto *models.ConsultationUpdateDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(id, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), id, dto)
}

// UpdateAnswers mocks base method.
func (m *MockService) UpdateAnswers(consultaID int, dto *models.AnswersUpdateDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnswers", consultaID, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnswers indicates an expected call of UpdateAnswers.
func (mr *MockServiceMockRecorder) UpdateAnswers(consultaID, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnswers", reflect.TypeOf((*MockService)(nil).UpdateAnswers), consultaID, dto)
}

// UpdateDiagnostic mocks base method.
func (m *MockService) UpdateDiagnostic(id int, dto *models.DiagnosticUpdateDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiagnostic", id, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDiagnostic indicates an expected call of UpdateDiagnostic.
func (mr *MockServiceMockRecorder) UpdateDiagnostic(id, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiagnostic", reflect.TypeOf((*MockService)(nil).UpdateDiagnostic), id, dto)
}

// UpdateTreatment mocks base method.
func (m *MockService) UpdateTreatment(id int, dto *models.TreatmentUpdateDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTreatment", id, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTreatment indicates an expected call of UpdateTreatment.
func (mr *MockServiceMockRecorder) UpdateTreatment(id, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTreatment", reflect.TypeOf((*MockService)(nil).UpdateTreatment), id, dto)
}
